model_list:
  # Local Ollama Models
  - model_name: llama3.2
    litellm_params:
      model: ollama/llama3.2:3b-instruct-q4_0
      api_base: http://ollama:11434

  # OpenRouter passthrough
  - model_name: openrouter/*
    litellm_params:
      model: openrouter/*
      api_base: https://openrouter.ai/api/v1
      api_key: os.environ/OPENROUTER_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true
  set_verbose: false
